# Data Analysis
## NumPy
NumPy is a library that adds support for large, multi-dimensional arrays and matrices to the Python programming language. It also offers a large collection of high-level mathematical functions to operate on these arrays. NumPy is free software released under the three-clause BSD license. It is the foundation of many other Python libraries for scientific computing - including pandas. Travis Oliphant is NumPy's original author.
### ndarray
At the heart of NumPy lies its n-dimensional array object. Each ndarray has a shape, a tuple indicating the size of each dimension.

In [1]:
import numpy as np
a = np.arange(0, 24)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [2]:
a = a.reshape(6,4)
print(a)
print(a.ndim)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2
(6, 4)


Arrays can be initialized from Python sequences. Alternatively, they can be created via `arange`, `zeros`, `ones` and `empty`.

In [3]:
np.array((1, 4, 2))

array([1, 4, 2])

In [4]:
np.array((1, 4, 2), dtype=np.float64)

array([1., 4., 2.])

In [5]:
np.zeros(12).reshape(3, 4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones(12).reshape(3, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.empty(12).reshape(3, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Operations between equal sized arrays applies the operation elementwise.

In [10]:
a * a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [11]:
a - a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
1 / a

/var/folders/xs/sw1srkwn5fjc523n7flyq3nc0000gn/T/ipykernel_19657/891846650.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / a


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826]])

In [13]:
a == 1

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Indexing and Slicing
One of the most important distinctions from Python lists is that array slices are views on the original array (instead of copies).

In [14]:
row = a[3]
row[-1] = 99
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 99],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Assignment of a scalar to a view is broadcast to the entire range.

In [15]:
a[1:4][:] = 0
a

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a[4, 0]

16

A boolean array can be passed for indexing.

In [17]:
homeworks = np.array(('hw_1', 'hw_2', 'hw_3', 'hw_4', 'hw_5', 'hw_6'))
print(homeworks == 'hw_5')
a[homeworks == 'hw_5']

[False False False False  True False]


array([[16, 17, 18, 19]])

In [18]:
r = np.random.randn(6, 4)
r

array([[ 0.08948199,  1.34279424, -0.68585454, -2.06278556],
       [-0.67083365, -0.51131186, -0.11542789,  2.00443519],
       [ 1.5740275 , -2.0001015 , -2.63070738, -0.57022777],
       [-0.72002533,  0.22788511, -0.17823538, -0.43296536],
       [-0.66270706, -0.05368031, -0.60567015,  1.40971251],
       [ 0.23308975,  0.0052887 , -0.11152013, -0.96203363]])

In [19]:
print(r < 0)
r[r < 0] = 0
r

[[False False  True  True]
 [ True  True  True False]
 [False  True  True  True]
 [ True False  True  True]
 [ True  True  True False]
 [False False  True  True]]


array([[0.08948199, 1.34279424, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.00443519],
       [1.5740275 , 0.        , 0.        , 0.        ],
       [0.        , 0.22788511, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.40971251],
       [0.23308975, 0.0052887 , 0.        , 0.        ]])

### Fancy Indexing
Uses integer arrays for indexing. Always creates copies of the data.

In [20]:
r[[-1, 4, 0]]

array([[0.23308975, 0.0052887 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.40971251],
       [0.08948199, 1.34279424, 0.        , 0.        ]])

In [21]:
t = r[[-1, 4, 0]]
t[:] = 0
t

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
r

array([[0.08948199, 1.34279424, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.00443519],
       [1.5740275 , 0.        , 0.        , 0.        ],
       [0.        , 0.22788511, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.40971251],
       [0.23308975, 0.0052887 , 0.        , 0.        ]])

### Universal Functions

In [23]:
np.sqrt(r)

array([[0.29913541, 1.15878999, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.41578077],
       [1.25460253, 0.        , 0.        , 0.        ],
       [0.        , 0.47737313, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.18731315],
       [0.48279369, 0.07272342, 0.        , 0.        ]])

In [24]:
r2 = np.random.randn(6, 4)
r2

array([[ 0.08710443,  0.14631283, -0.85463782, -0.39599897],
       [ 1.36402999, -0.78081835, -0.62772867, -2.56082049],
       [-0.16457187,  0.26415489,  0.4114528 ,  1.41645843],
       [ 1.2377916 ,  0.10118642,  1.82290632,  0.17459472],
       [-0.30168452,  1.61319617, -1.42408186,  0.71926724],
       [ 1.31938284,  0.08310792,  1.13738667,  0.78420051]])

In [25]:
np.maximum(r, r2)

array([[0.08948199, 1.34279424, 0.        , 0.        ],
       [1.36402999, 0.        , 0.        , 2.00443519],
       [1.5740275 , 0.26415489, 0.4114528 , 1.41645843],
       [1.2377916 , 0.22788511, 1.82290632, 0.17459472],
       [0.        , 1.61319617, 0.        , 1.40971251],
       [1.31938284, 0.08310792, 1.13738667, 0.78420051]])

Counting True values:

In [26]:
(r2 > 0).sum()

16

### Conditional Logic

In [39]:
xs = np.arange(0, 1, 0.1)
ys = np.arange(1, 2, 0.1)
cs = np.array((True, False, False, True, False, True, True, True, False, True))
print(xs, ys, cs, sep='\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[ True False False  True False  True  True  True False  True]


In [40]:
[(x if c else y) for x, y, c in zip(xs, ys, cs)]

[0.0,
 1.1,
 1.2000000000000002,
 0.30000000000000004,
 1.4000000000000004,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 1.8000000000000007,
 0.9]

In [41]:
np.where(cs, xs, ys)

array([0. , 1.1, 1.2, 0.3, 1.4, 0.5, 0.6, 0.7, 1.8, 0.9])

In [42]:
np.where(r2 > 0, 'Chris', 'Pat')

array([['Chris', 'Chris', 'Pat', 'Pat'],
       ['Chris', 'Pat', 'Pat', 'Pat'],
       ['Pat', 'Chris', 'Chris', 'Chris'],
       ['Chris', 'Chris', 'Chris', 'Chris'],
       ['Pat', 'Chris', 'Pat', 'Chris'],
       ['Chris', 'Chris', 'Chris', 'Chris']], dtype='<U5')

### Statistical Operations

In [43]:
r2.mean()

0.23217463508338512

In [44]:
print(r2)
r2.cumsum()

[[ 0.08710443  0.14631283 -0.85463782 -0.39599897]
 [ 1.36402999 -0.78081835 -0.62772867 -2.56082049]
 [-0.16457187  0.26415489  0.4114528   1.41645843]
 [ 1.2377916   0.10118642  1.82290632  0.17459472]
 [-0.30168452  1.61319617 -1.42408186  0.71926724]
 [ 1.31938284  0.08310792  1.13738667  0.78420051]]


array([ 0.08710443,  0.23341726, -0.62122056, -1.01721953,  0.34681046,
       -0.43400789, -1.06173656, -3.62255705, -3.78712892, -3.52297403,
       -3.11152122, -1.69506279, -0.45727119, -0.35608478,  1.46682154,
        1.64141627,  1.33973174,  2.95292791,  1.52884605,  2.2481133 ,
        3.56749614,  3.65060406,  4.78799073,  5.57219124])

### Sorting

In [45]:
r = np.random.randn(6, 4)
r

array([[-0.40088067,  2.22273446,  0.36045444,  0.46634473],
       [-0.32159961,  0.2282196 ,  0.87363388,  0.90200893],
       [ 0.86231654, -1.34943561,  0.01308708, -0.00740041],
       [ 0.95943336,  0.87044295, -0.60528588, -1.88813755],
       [ 1.20748209, -0.19741552,  1.95416666, -2.3863287 ],
       [ 0.99128149, -0.14512482, -0.02294771,  0.19210266]])

In [46]:
r.sort()
r

array([[-0.40088067,  0.36045444,  0.46634473,  2.22273446],
       [-0.32159961,  0.2282196 ,  0.87363388,  0.90200893],
       [-1.34943561, -0.00740041,  0.01308708,  0.86231654],
       [-1.88813755, -0.60528588,  0.87044295,  0.95943336],
       [-2.3863287 , -0.19741552,  1.20748209,  1.95416666],
       [-0.14512482, -0.02294771,  0.19210266,  0.99128149]])

In [47]:
r.sort(0)
r

array([[-2.3863287 , -0.60528588,  0.01308708,  0.86231654],
       [-1.88813755, -0.19741552,  0.19210266,  0.90200893],
       [-1.34943561, -0.02294771,  0.46634473,  0.95943336],
       [-0.40088067, -0.00740041,  0.87044295,  0.99128149],
       [-0.32159961,  0.2282196 ,  0.87363388,  1.95416666],
       [-0.14512482,  0.36045444,  1.20748209,  2.22273446]])

### Linear Algebra
Matrix operations like inverse and determinant are using the same industry standard Fortran libraries (eg. BLAS, LAPACK) that are also used in other matrix languages - including some of NumPy's commercial counterparts. 

In [48]:
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
Y = np.arange(10, 4, -1).reshape(2, 3)
Y

array([[10,  9,  8],
       [ 7,  6,  5]])

In [50]:
Z = X.dot(Y)
Z

array([[ 7,  6,  5],
       [41, 36, 31],
       [75, 66, 57]])

In [51]:
M = np.matrix(Z)
M.I

matrix([[-8.68080113e+13,  1.73616023e+14, -8.68080113e+13],
        [ 1.73616023e+14, -3.47232045e+14,  1.73616023e+14],
        [-8.68080113e+13,  1.73616023e+14, -8.68080113e+13]])

In [52]:
from numpy.linalg import inv
inv(Z)

array([[-8.68080113e+13,  1.73616023e+14, -8.68080113e+13],
       [ 1.73616023e+14, -3.47232045e+14,  1.73616023e+14],
       [-8.68080113e+13,  1.73616023e+14, -8.68080113e+13]])

### Random Numbers
NumPy provides generators for random numbers following different distributions.

In [53]:
np.random.normal(size=(6, 4))

array([[ 0.89512936,  0.34853506,  0.04293267,  1.2902801 ],
       [-0.28337573,  1.61738367,  1.00762135, -1.19459758],
       [-0.21691876,  0.51964119, -0.71632704,  0.15720208],
       [-0.96144617, -1.60056598,  1.14569072, -0.26043004],
       [ 1.01809438, -0.48340502,  1.13137671,  0.97225524],
       [-1.96590309,  1.76855905,  0.30508334, -0.31329364]])

In [54]:
np.random.chisquare(3, size=(6, 4))

array([[1.78338424, 1.05441781, 1.62725596, 1.35656077],
       [2.61910334, 4.2950916 , 0.74438914, 0.73064184],
       [4.34061692, 1.94876561, 0.45954278, 5.05700555],
       [5.42243482, 4.97306959, 6.73083609, 3.22701699],
       [0.2129075 , 1.2624982 , 2.41236297, 4.59165851],
       [5.09804669, 1.89806386, 0.77218602, 2.81388723]])

## pandas

This library offers facilities for data manipulation and analysis. It contains the `Series` and `DataFrame` data structures that allow efficient manipulation and analysis of one and two dimensional data. Pandas is free software released under the three-clause BSD license. Its name is derived from "panel data", an econometrics term for multidimensional structured data sets. Pandas was originally written by Wes McKinney.

In [55]:
import pandas as pd
from pandas import DataFrame, Series

### Series and DataFrame
The `Series` and `Dataframe` types are close relatives to the numpy `ndarray` but allow for labelling the data. The labels are called index. Since a `Series` is one-dimensional it can be compared with a Python `dict`.

In [56]:
s = Series((4, 2, 3, 5, 7))
s

0    4
1    2
2    3
3    5
4    7
dtype: int64

In [57]:
s.values

array([4, 2, 3, 5, 7])

In [58]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [59]:
s = Series((4, 2, 3, 5, 7), index=['Sue', 'Pat', 'Chris', 'John', 'Stu'])
s

Sue      4
Pat      2
Chris    3
John     5
Stu      7
dtype: int64

In [60]:
s[['Chris', 'John', 'Sue']]

Chris    3
John     5
Sue      4
dtype: int64

A `DataFrame` represents tabular data much like the common spreadsheet programs or a single table in a database. Each column can have a different datatype. It behaves similar to a `dict` of `Series`.

In [61]:
d = DataFrame({'student': ['Pat', 'Pat', 'Chris', 'Chris'],
               'homework': [1, 1, 2, 2],
               'points': [9, 9, 7, 8]})
d

student  homework  points
0     Pat         1       9
1     Pat         1       9
2   Chris         2       7
3   Chris         2       8

In [62]:
d['points'].describe()

count    4.000000
mean     8.250000
std      0.957427
min      7.000000
25%      7.750000
50%      8.500000
75%      9.000000
max      9.000000
Name: points, dtype: float64

Even though it is possible to create DataFrames from scratch it is most common to load the data from external files or databases.

In [63]:
[method for method in dir(pd) if method.startswith('read')]

['read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml']

Let's dive into a small real-life example.
### Analyzing a Photovoltaic Powerplant's Log File

As it happens, there's interesting data worth analysis everywhere. The data we're looking at was taken from a power inverter installed in my basement.
CSV files quickly get large. Fortunately, pandas can open compressed csv files on-the-fly (the data is available at [pv_data.csv.bz2](http://www.senarclens.eu/~gerald/teaching/cms/notebooks/pv_data.csv.bz2)).

In [64]:
df = pd.read_csv('pv_data.csv.bz2', sep=';', skiprows=1)
df.tail()

FileNotFoundError: [Errno 2] No such file or directory: 'pv_data.csv.bz2'

Let's try to find out how much energy was produced. We could start by transforming the data into a more common unit.

In [65]:
df.columns

NameError: name 'df' is not defined

That's more columns than we're interested in. Let's drop the rest.

In [66]:
df.drop(['Inverter No.', 'Device Type', 'Reactive Energy L[Vars]', 'Reactive Energy C[Vars]',
       'Uac L1 [V]', 'Uac L2 [V]', 'Uac L3 [V]', 'Iac L1 [A]', 'Iac L2 [A]',
       'Iac L3 [A]', 'Udc MPPT1[V]', 'Idc MPPT1[A]', 'Udc MPPT2[V]',
       'Idc MPPT2[A]', 'Description'], axis=1, inplace=True)
df.head()

NameError: name 'df' is not defined

In [67]:
df['Wh'] = df['Energy [Ws]'] / 3600
df['Wh'].tail()

NameError: name 'df' is not defined

Maybe the data would be even nicer and easier to understand in the more common kWh unit.

In [ ]:
df['kWh'] = df['Wh'] / 1000
df['kWh'].tail()

A quick peak at some basic statistics.

In [ ]:
df['kWh'].describe()

In [ ]:
df['kWh'].sum()

Lookslike about 5.2 MWh were produced during the entire time. How long was the log recorded?

In [ ]:
df['Date'] = df['Date'].astype('datetime64')
delta = df['Date'].max() - df['Date'].min()
delta

So how much produces this power plant roughly per year?

In [ ]:
df['kWh'].sum() / delta.days * 365

Is this value correct? Maybe the 477 days included two winters and only one summer?

In [ ]:
df['Date'].head()

In [ ]:
df['Date'].tail()

A straight-forward solution would be to limit the date to the (entire) year 2016. Pandas can do the job.

In [ ]:
df['Year'] = pd.DatetimeIndex(df['Date']).year
df[df['Year'] == 2016].head()

In [ ]:
df[df['Year'] == 2016].tail()

In [ ]:
df_2016 = df[df['Year'] == 2016]
df_2016['kWh'].sum()

Finally it looks like that the power plant produces roughly 5 MWh per year - almost enough for a household of 4 persons.
How did the production distribute over the year?

In [ ]:
grouped = df_2016.groupby('Date').sum()
grouped.tail()

A chart would be much easier to grasp...

In [ ]:
%matplotlib inline
grouped.plot(y='kWh', title='2016 PV Output', figsize = (12, 12))

There is so much more to pandas. Please dive in and enjoy all the cool things you can do. I highly recommend Wes McKinney's (creator of pandas) excellent book [Python for Data Analysis](http://amzn.to/2rKFHby). Starting in fall 2017, the [2nd edition](http://amzn.to/2sHWH7B) will be available.

Since I was recently asked whether pandas can combine dataframse in an SQL manner - yes. Pandas rocks: https://pandas.pydata.org/pandas-docs/stable/merging.html#database-style-dataframe-joining-merging